CREATE DATABASE Nyous;

CREATE TABLE Acesso(
IdAcesso INT IDENTITY PRIMARY KEY NOT NULL,
Tipo VARCHAR(50)
);

CREATE TABLE Categoria(
IdCategoria INT IDENTITY PRIMARY KEY NOT NULL,
Titulo VARCHAR(50) NOT NULL
);

CREATE TABLE Localizacao(
IdLocalizacao INT IDENTITY PRIMARY KEY NOT NULL,
Logradouro VARCHAR(50) NOT NULL,
Numero VARCHAR(50),
Complemento VARCHAR(50),
Bairro VARCHAR(50),
Cidade VARCHAR(50),
UF VARCHAR(2),
CEP VARCHAR(50)
);

CREATE TABLE Usuario(
IdUsuario INT IDENTITY PRIMARY KEY NOT NULL,
Nome VARCHAR(100) NOT NULL,
Email VARCHAR(80) NOT NULL,
Senha VARCHAR(100) NOT NULL,
DataNascimento DATETIME,

IdAcesso INT FOREIGN KEY REFERENCES Acesso (IdAcesso)
);


CREATE TABLE Evento(
IdEvento INT IDENTITY PRIMARY KEY NOT NULL,
Evento DATETIME NOT NULL,
AcessoRestrito BINARY DEFAULT 0,
Capacidade INT NOT NULL,
Descricao VARCHAR(255),


IdLocalizacao INT FOREIGN KEY REFERENCES Localizacao (IdLocalizacao),
IdCategoria INT FOREIGN KEY REFERENCES Categoria (IdCategoria)
);

CREATE TABLE Convite(
IdConvite INT PRIMARY KEY IDENTITY NOT NULL,
Confirmado BIT DEFAULT NULL,


IdEvento INT FOREIGN KEY REFERENCES Evento (IdEvento),
IdUsuarioEmissor INT FOREIGN KEY REFERENCES Usuario (IdUsuario),
IdUsuarioConvidado INT FOREIGN KEY REFERENCES Usuario (IdUsuario),
);

CREATE TABLE Presenca(
IdPresenca INT PRIMARY KEY IDENTITY NOT NULL,
Confirmado BIT DEFAULT NULL,



IdEvento INT FOREIGN KEY REFERENCES Evento (IdEvento),
IdUsuario INT FOREIGN KEY REFERENCES Usuario (IdUsuario),
);